apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-deployment
spec:
  selector:
    matchLabels:
      app: cicd-demo-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: cicd-demo-app
    spec:
      containers:
      - name: cicd-demo-app
        image: helderklemp/cicd-demo:${IMAGE_TAG}
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management

          